# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0002_note_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='mynote.Note')),
            ],
        ),
    ]
