# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0004_auto_20180103_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='mynote.Label'),
        ),
    ]
