# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0005_auto_20180103_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.CharField(blank=True, default=False, max_length=200, null=True, verbose_name='mynote.Label'),
        ),
    ]
