# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0006_auto_20180109_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.ForeignKey(blank=True, default=False, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='mynote.Label'),
        ),
    ]
